del /q /s *.cbk
del /q /s *.drc
del /q /s *.dsk
del /q /s *.dsm
del /q /s *.identcache
del /q /s *.local
del /q /s *.map
rmdir /Q /S Source\__history
rmdir /Q /S Packages\__history
rmdir /Q /S Library\D2010
rmdir /Q /S Library\DXE4
rmdir /Q /S Library\DXE5
